name: Deploy samples to Netlify
env:
  NODE_VERISON: 14
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - samples/weatherforecast/

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn Dependencies
        run: yarn install --cwd samples/weather-forecast --frozen-lockfile

      - name: Build widget
        run: yarn --cwd samples/weather-forecast build

      - name: Prepare Deployment
        run: |
          mkdir samples/deploy
          cp samples/netlify.toml samples/deploy/
          cp samples/weather-forecast/dist/* samples/deploy/

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=samples/deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
